### PR TITLE
Upgrade projects to netcoreapp3.0

### PR DESCRIPTION
**Pull request by natemcmaster**
Upgrade this project to netcoreapp3.0.

Marking as wip: because this causes test failures which I'm not 100% how to fix. It looks like the tests expect the samples to have a certain TFM. cc @pakrym can you help?

Part of https://github.com/aspnet/AspNetCore/issues/3754

### CODE REVIEW

**Comment by natemcmaster** [comment]
JavaScriptSnippetTests are failing, presumably because they are trying to publish netcoreapp2.0 and 2.1 projects. Are these tests for backwards compatibility? Or should the also change to 3.0?

**Comment by pakrym** [comment]
@muratg do we want to continue running tests against AI adapter? I don't think they realize we do this and seem to be doing fine.

**Comment by muratg** [comment]
@pakrym what adapter? It's OK to disable tests to move forward with 3.0 port.  What of our scenarios do these tests test? 
> I don't think they realize we do this and seem to be doing fine.

Let's make sure :)

**Comment by pakrym** [comment]
We are running tests against `Microsoft.ApplicationInsights.AspNetCore`. We don't own the scenario anymore we were just running them during transition time to make sure things go smooth.

**Comment by natemcmaster** [comment]
Tests pass now :)

**Comment by pakrym** [comment]
AI has it's new hosting startup here https://mseng.visualstudio.com/AppInsights/_git/StatusMonitor?path=%2FExtensions%2FExtension%2FAspNetCore.HostingStartup&version=GBmaster

And it's running a lot more tests than we did: https://github.com/Microsoft/ApplicationInsights-aspnetcore/tree/develop/test/Microsoft.ApplicationInsights.AspNetCore.Tests

**Pull request merged**
