### PR TITLE
Add // <auto-generated /> to _AssembyInfo.KeyVaultHostingStartup.cs

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by pakrym** [comment]
In case customers use FxCop

**Comment by natemcmaster** [comment]
`release/2.0`? Which release is this targeting?

**Comment by AArnott** [comment]
> In case customers use FxCop

StyleCop, actually. This change shouldn't impact FxCop at all.

@natemcmaster: This should (please) target the first stable release of the package in question (or a preview of the same).

**Comment by pakrym** [comment]
@natemcmaster OOB of KeyVault HostingStartup

**Pull request merged**
