### PR TITLE
Remove unused content from logging site extension

### PR DESCRIPTION
**Pull request by pakrym**
applicationHost and scmApplicationHost are now packed in https://github.com/aspnet/AspNetCore/blob/master/src/SiteExtensions/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj

### CODE REVIEW

**Comment by natemcmaster** [comment]
Build failures:

> D:\a\1\s\.dotnet\x64\sdk\2.2.100-preview2-009404\Microsoft.Common.CurrentVersion.targets(4533,5): error MSB3030: Could not copy the file "D:\a\1\s\extensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\applicationHost.xdt" because it was not found. [D:\a\1\s\test\Microsoft.AspNetCore.AzureAppServices.SiteExtension.Tests\Microsoft.AspNetCore.AzureAppServices.SiteExtension.Tests.csproj]

**Comment by pakrym** [comment]
There were some tests using the XDT file, moved them in https://github.com/aspnet/AspNetCore/pull/3726

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
Btw, I noticed this PR targets master, but https://github.com/aspnet/AspNetCore/pull/3726 targets release/2.2. Any reason for the difference?

**Comment by pakrym** [comment]
I'm too used to having release/2.2 as default branch.

**Pull request merged**
