### PR TITLE
Revert hosting startup packages to netcoreapp2.0 only

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/aspnet/AzureIntegration/issues/66

### CODE REVIEW

**Comment by pranavkm** [comment]
Looks good to me.

**Comment by Tratcher** [comment]
?? The feature still works for net461, only the assembly discovery is different.

**Comment by pakrym** [comment]
Hm, I thought hosting startups were for core only. Closing.

**Comment by pranavkm** [comment]
Should we cross-compile this project in that case?

**Comment by pakrym** [comment]
Why is it required?

**Comment by pranavkm** [comment]
`Microsoft.AspNetCore.ApplicationInsights.HostingStartup` references the `net461` build of `Microsoft.Extensions.DiagnosticAdapter` (which is cross-compiled for `netcoreapp2.0` and `net461`). I'd rather we cross-compile and avoid the warning.

**Comment by pakrym** [comment]
@Tratcher is cross-compiling fine?

**Comment by Tratcher** [comment]
Cross compiling should be fine.

**Pull request closed without merging**
