### PR TITLE
Add site extension store and additonal deps environment variables

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by Tratcher** [comment]
Only for preview? Will we remove this in RTM?

**Comment by pakrym** [comment]
Both preview and RTM

**Comment by Tratcher** [comment]
Where's the work item for this?
Why include AzureKeyVault from the extensions dir but not from program files?

**Comment by pakrym** [comment]
Part of https://github.com/aspnet/AzureIntegration/issues/143.
Program files is there to keep backwards compatibility for 2.0 apps and there was no KeyVault startup in 2.0.

**Pull request merged**
