### PR TITLE
Update AspNetCoreRuntime package properties

### PR DESCRIPTION
**Pull request by pakrym**
Use common properties for owner/icon/copyright etc.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
@Eilon 
Shouldn't he be looking at this?

**Comment by Tratcher** [comment]
Many of these are normally set by the build. Is this package too special for that?

**Comment by pakrym** [comment]
Added a reference to internal sdk, extracted common properties.

**Comment by Eilon** [comment]
So this package will now just have the same metadata as everything else? That sounds good, though I wouldn't approve this PR for preview1 if that's *all* that's here. I assume this PR changes other more important things that we do need for Preview1? If so, approved.

**Comment by pakrym** [comment]
@Eilon No, it's about description and other metadata.

**Comment by Eilon** [comment]
Ok then approved.

**Pull request merged**
